facet.widget.config.facets_form_dropdown:
  type: facet.widget.default_config
  label: 'Dropdown (inside form) widget configuration'
  mapping:
    default_option_label:
      type: label
      label: 'Default option label'
    child_items_prefix:
      type: text
      label: 'Child item prefix'

block.settings.facets_form:*:
  type: block_settings
  label: 'Facets form block'
  mapping:
    submit_text:
      type: string
      label: 'Search'
    reset_text:
      type: string
      label: 'Clear filters'
