facet.widget.facets_form_default_config:
  type: facet.widget.default_config
  label: 'Default config for facets form widgets'
  mapping:
    disabled_on_empty:
      type: boolean
      label: 'Disable on empty'

facet.widget.config.facets_form_dropdown:
  type: facet.widget.facets_form_default_config
  label: 'Dropdown (inside form) widget configuration'
  mapping:
    default_option_label:
      type: label
      label: 'Default option label'
    child_items_prefix:
      type: text
      label: 'Child item prefix'

facet.widget.config.facets_form_checkbox:
  type: facet.widget.facets_form_default_config
  label: 'Checkboxes (inside form) widget configuration'
  mapping:
    indent_class:
      type: string
      label: 'Indentation class'

block.settings.facets_form:*:*:
  type: block_settings
  label: 'Facets form block'
  mapping:
    button:
      type: mapping
      label: Button
      mapping:
        label:
          type: mapping
          label: Label
          mapping:
            submit:
              type: label
              label: Submit
            reset:
              type: label
              label: Clear filters
    facets:
      type: sequence
      label: 'Display facets'
      sequence:
        type: string
        label: 'Facet option'
